[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bro"
version = "0.1.0"
description = "AI assistant for lazy people."
authors = [
    { name = "Cyan Ding", email = "blueplus.d@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "playwright",
    "patchright",
    "python-dotenv",
    "aiohttp",
    "pytest",
    "pytest-asyncio",
    "ruff>=0.12.0",
    "pre-commit>=3.5.0",
    "pydantic>=2.10.6",
    "cerebras-cloud-sdk>=1.35.0",
    "opencv-python",
    "ultralytics",
    "numpy",
    "Pillow",
    "tqdm",
    "scipy",
    "matplotlib",
    "pytz",
    "pandas",
    "requests",
    "scikit-learn",
    "typing-extensions",
    "beautifulsoup4",
]

[tool.setuptools.packages.find]
where = ["bro"]
