[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bro"
version = "0.1.0"
description = "AI assistant for lazy people."
authors = [
    { name = "Cyan Ding", email = "blueplus.d@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "playwright",
    "patchright",
    "python-dotenv",
    "aiohttp",
    "pytest",
    "pytest-asyncio",
    "ruff==0.12.7",
    "pre-commit",
    "pydantic",
    "cerebras-cloud-sdk",
    "anthropic",
    "openai",
    "chardet",
    "deptry==0.23.1",
    "faiss-cpu",
    "numpy",
    "markdownify>=1.2.0",
    "beautifulsoup4>=4.13.4",
]

[tool.setuptools.packages.find]
where = ["bro"]
