import json
import uuid

from worker import Worker

from tools.ai import load_sys_prompt, openrouter


class Manager:
    def __init__(self, subgoal):
        self.subgoal = subgoal
        self.workers = []
        self.task_queue = []
        self.completed_tasks = []
        self.progress_tasks = []
        self.id = uuid.uuid4()

    # here's where the llm will split the self.task into many tasks, add them to task_queue, and then assign tasks
    async def create_tasks(self):
        sys_prompt = await load_sys_prompt("manager")
        subgoal_json = json.dumps(self.subgoal)
        result = await openrouter(subgoal_json, sys_prompt)

        if "atomic_tasks" in result:
            self.task_queue = result["atomic_tasks"]
        else:
            print("No atomic tasks generated by manager")

    # add a worker
    def add_worker(self, worker: Worker):
        self.workers.append(worker)
        worker.set_manager(self)

    # assign a task to a worker, if it doesn't exist, make a new one
    def assign_task(self, task, worker_id):
        assigned_worker = next(
            (worker for worker in self.workers if worker.id == worker_id), None
        )

        if assigned_worker is not None:
            assigned_worker.receive_task(task)

    # add a task (either succesful or in question to the manager llm)
    def receive_update(self, message):
        self.progress_tasks.append(message)

    async def execute(self):
        print(f"Running processes of manager {self.id}")
        await self.create_tasks()

        for atomic_task in self.task_queue:
            worker = Worker(atomic_task)
            self.add_worker(worker)
            await worker.execute_task()
