from roles.manager import Manager

from actions.ai import load_sys_prompt, openrouter


class Ceo:
    def __init__(self, task: str) -> None:
        self.task = task
        self.divided_tasks = []
        self.managers = []

    # Todo: use ai system prompt to extract high level tasks from the prompt
    # then, spawn in a number of managers to execute those tasks
    async def execute(self):
        sys_prompt = await load_sys_prompt("ceo")
        result = await openrouter(self.task, sys_prompt)

        if "subgoals" in result:
            self.divided_tasks = result["subgoals"]

            for subgoal in self.divided_tasks:
                manager = Manager(subgoal)
                self.managers.append(manager)
                await manager.execute()

        else:
            print("No subgoals generated by Ceo")
