import asyncio
import json
import uuid

from roles.worker import Worker
from typing import cast, List
from actions.ai import load_sys_prompt, cerebras


class Manager:
    def __init__(self, subgoal: str):
        self.subgoal = subgoal
        self.workers = []
        self.task_queue = []
        self.completed_tasks = []
        self.progress_tasks = []
        self.id = uuid.uuid4()

    # here's where the llm will split the self.task into many tasks, add them to task_queue, and then assign tasks
    async def create_tasks(self):
        sys_prompt = await load_sys_prompt("manager")
        llm_res = await cerebras(self.subgoal, sys_prompt)
        llm_res = cast(List, llm_res.to_dict()["choices"])[0]["message"]["content"]
        llm_json = json.loads(llm_res)
        if "atomic_tasks" in llm_json.keys():
            self.task_queue = llm_json["atomic_tasks"]
            print(self.task_queue)
        else:
            print("No atomic tasks generated by manager")

    # add a worker
    def add_worker(self, worker: Worker):
        self.workers.append(worker)
        worker.set_manager(self)

    # assign a task to a worker, if it doesn't exist, make a new one
    def assign_task(self, task, worker_id):
        assigned_worker = next(
            (worker for worker in self.workers if worker.id == worker_id), None
        )

        if assigned_worker is not None:
            assigned_worker.receive_task(task)

    # add a task (either succesful or in question to the manager llm)
    def receive_update(self, message):
        self.progress_tasks.append(message)

    async def execute(self):
        print(f"Running processes of manager {self.id}")
        await self.create_tasks()

        for atomic_task in self.task_queue:
            worker = Worker(atomic_task)
            self.add_worker(worker)
            await worker.execute_task()


async def main():
    manager = Manager(
        "Collect information from chat gpt on how to set up a windows computer"
    )
    await manager.create_tasks()


if __name__ == "__main__":
    asyncio.run(main())
